// Generated by scripts/sync-android-brand.mjs from gecko-chrome/branding/navis-mark.json; do not edit.
package org.navis.browser.ui

internal object NavisBrandGeometry {
    const val VIEWPORT = 220f
    const val CORNER_RADIUS = 40f
    const val ROTATION = 42f
    const val CONTOUR_X = 22f
    const val CONTOUR_Y = 22f
    const val CONTOUR_WIDTH = 176f
    const val CONTOUR_HEIGHT = 176f
    const val CENTER_X = 110f
    const val CENTER_Y = 110f
    const val CHANNEL_WIDTH = 22.5f
    const val CHANNEL_OPACITY = 0.8f
    const val SEAM_WIDTH = 6.8f
    const val SEAM_DASH = 260f
    const val BASE_MILLISECONDS = 720f
    const val BASE_OPAQUE_AT = 0.62f
    const val SEAM_DELAY_MILLISECONDS = 420f
    const val SEAM_MILLISECONDS = 920f
    const val INTRO_MILLISECONDS = 1340f
    const val HEAD_MILLISECONDS = 1600f
    const val PARTICLE_MILLISECONDS = 2600f
    const val OVERLAY_MILLISECONDS = 320f
    const val OVERLAY_INITIAL_SCALE = 0.982f
    const val HEAD_RADIUS = 4.5f
    const val RIM_WIDTH = 0.95f
    const val RIM_OPACITY = 0.42f
    const val CHANNEL = "M127.4 239.9 L108 217 C91 197 62 154 64 133 C66 112 83 105 103 108 C123 111 159 91 165 61 C168 46 164 32 160 25 L145.1 -1"
    const val SEAM_A = "M127.4 239.9 L108 217 C91 197 62 154 64 133 C66 112 83 105 103 108"
    const val SEAM_B = "M145.1 -1 L160 25 C164 32 168 46 165 61 C161.1 80.5 144.525 95.775 127.908 103.255"
    val BASE_EASING = floatArrayOf(0.2f, 0.82f, 0.22f, 1f)
    val SEAM_EASING = floatArrayOf(0.62f, 0.02f, 0.22f, 1f)
    val HEAD_EASING = floatArrayOf(0.45f, 0f, 0.35f, 1f)
    val HEAD_SCALE = floatArrayOf(0.94f, 1.1f, 0.94f)
    val HEAD_KEY_TIMES = floatArrayOf(0f, 0.45f, 1f)
    val CONTOUR_COLORS = longArrayOf(0xFF448AFF, 0xFF536FE7, 0xFF7355DB)
    val CONTOUR_STOPS = floatArrayOf(0f, 0.54f, 1f)
    val CONTOUR_POSITION = floatArrayOf(35f, 32f, 176f, 190f)
    val CHANNEL_COLORS = longArrayOf(0xFF4082F0, 0xFF4E68D9, 0xFF6C50CE)
    val CHANNEL_STOPS = floatArrayOf(0f, 0.54f, 1f)
    val CHANNEL_POSITION = floatArrayOf(35f, 32f, 176f, 190f)
    val FROST_DIFFUSE_COLORS = longArrayOf(0x33F7F9FF, 0x17EDF1FF, 0x00DFE6FF)
    val FROST_DIFFUSE_STOPS = floatArrayOf(0f, 0.42f, 1f)
    val FROST_DIFFUSE_POSITION = floatArrayOf(106.48f, 95.92f, 119.68f)
    val FROST_FOG_COLORS = longArrayOf(0x00FFFFFF, 0x14E8EEFF, 0x3D9CA7D6)
    val FROST_FOG_STOPS = floatArrayOf(0f, 0.56f, 1f)
    val FROST_FOG_POSITION = floatArrayOf(131.12f, 159.28f, 151.36f)
    val RIM_COLORS = longArrayOf(0x3DEFF4FF, 0x29D3DDEF, 0x2E6F7AAF)
    val RIM_STOPS = floatArrayOf(0f, 0.58f, 1f)
    val RIM_POSITION = floatArrayOf(22f, 22f, 22f, 198f)
    val particles = listOf(
        Particle(floatArrayOf(-5f, 5f), 2f, 0.846f, floatArrayOf(1f, 0.74f, 0.74f, 1f), floatArrayOf(0f, 0.34f, 0.76f, 1f), floatArrayOf(0f, 0.9f, 0f, 0f), floatArrayOf(0f, 0.04f, 0.36f, 1f)),
        Particle(floatArrayOf(6.5f, -6.5f), 1.55f, 0.7332f, floatArrayOf(1f, 1f, 0.7f, 0.7f, 1f), floatArrayOf(0f, 0.2f, 0.54f, 0.8f, 1f), floatArrayOf(0f, 0f, 0.82f, 0f, 0f), floatArrayOf(0f, 0.2f, 0.24f, 0.56f, 1f)),
        Particle(floatArrayOf(-8f, 8f), 1.2f, 0.6392f, floatArrayOf(1f, 1f, 0.66f, 0.66f, 1f), floatArrayOf(0f, 0.4f, 0.74f, 0.84f, 1f), floatArrayOf(0f, 0f, 0.74f, 0f, 0f), floatArrayOf(0f, 0.4f, 0.44f, 0.76f, 1f)),
        Particle(floatArrayOf(5f, -5f), 0.9f, 0.5452f, floatArrayOf(1f, 1f, 0.62f, 0.62f, 1f), floatArrayOf(0f, 0.6f, 0.94f, 0.97f, 1f), floatArrayOf(0f, 0f, 0.66f, 0f, 0f), floatArrayOf(0f, 0.6f, 0.64f, 0.96f, 1f))
    )
    val contourRelief = listOf(Relief(-0.8f, -1.2f, 0xFFD7E4FF, 0.22f), Relief(1.2f, 1.4f, 0xFF07122F, 0.2f))
    val channelRelief = listOf(Relief(-0.5f, -0.9f, 0xFFDCE8FF, 0.3f), Relief(0.8f, 1.4f, 0xFF071136, 0.38f))
    val seamRelief = listOf(Relief(-0.6f, -0.6f, 0xFFFFFFFF, 0.32f), Relief(0.5f, 0.8f, 0xFF0B1438, 0.3f))
    data class Particle(val offsets: FloatArray, val radius: Float, val alpha: Float, val positions: FloatArray, val times: FloatArray, val opacities: FloatArray, val opacityTimes: FloatArray)
    data class Relief(val x: Float, val y: Float, val color: Long, val alpha: Float)
}
