# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'cid': '{f993a34e-7bbf-47fb-9f14-07ccf8903b35}',
        'contract_ids': ['@mozilla.org/network/protocol;1?name=navis'],
        'esModule': 'resource://gre/modules/DesktopNavisProtocolHandler.sys.mjs',
        'constructor': 'DesktopNavisProtocolHandler',
        'protocol_config': {
            'scheme': 'navis',
            'flags': [
                'URI_STD',
                'URI_DANGEROUS_TO_LOAD',
                'URI_IS_LOCAL_RESOURCE',
                'URI_IS_POTENTIALLY_TRUSTWORTHY',
                'URI_HAS_WEB_EXPOSED_ORIGIN',
            ],
        },
    },
]
